services:
  postgres:
    image: postgres:16
    container_name: edip-postgres
    environment:
      POSTGRES_DB: edip
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - edip_postgres_data:/var/lib/postgresql/data

volumes:
  edip_postgres_data:
